/**
 * Wie weit weg – Städte-Distanzen zur Bezugsstadt Köln
 * Format: Start;Stadt;Land;Distanz_km
 */
export const BEZUGSSTADT = 'Köln'

export const CITIES_DATA = [
  { stadt: 'Bonn', land: 'Deutschland', distanz_km: 25 },
  { stadt: 'Wuppertal', land: 'Deutschland', distanz_km: 40 },
  { stadt: 'Mönchengladbach', land: 'Deutschland', distanz_km: 49 },
  { stadt: 'Bochum', land: 'Deutschland', distanz_km: 65 },
  { stadt: 'Münster', land: 'Deutschland', distanz_km: 124 },
  { stadt: 'Wiesbaden', land: 'Deutschland', distanz_km: 132 },
  { stadt: 'Luxemburg', land: 'Luxemburg', distanz_km: 158 },
  { stadt: 'Bielefeld', land: 'Deutschland', distanz_km: 163 },
  { stadt: 'Brüssel', land: 'Belgien', distanz_km: 183 },
  { stadt: 'Mannheim', land: 'Deutschland', distanz_km: 201 },
  { stadt: 'Amsterdam', land: 'Niederlande', distanz_km: 214 },
  { stadt: 'Hannover', land: 'Deutschland', distanz_km: 251 },
  { stadt: 'Karlsruhe', land: 'Deutschland', distanz_km: 259 },
  { stadt: 'Braunschweig', land: 'Deutschland', distanz_km: 287 },
  { stadt: 'Erfurt', land: 'Deutschland', distanz_km: 288 },
  { stadt: 'Freiburg im Breisgau', land: 'Deutschland', distanz_km: 333 },
  { stadt: 'Nürnberg', land: 'Deutschland', distanz_km: 336 },
  { stadt: 'Magdeburg', land: 'Deutschland', distanz_km: 356 },
  { stadt: 'Paris', land: 'Frankreich', distanz_km: 403 },
  { stadt: 'Augsburg', land: 'Deutschland', distanz_km: 425 },
  { stadt: 'Chemnitz', land: 'Deutschland', distanz_km: 425 },
  { stadt: 'Kiel', land: 'Deutschland', distanz_km: 434 },
  { stadt: 'Vaduz', land: 'Liechtenstein', distanz_km: 447 },
  { stadt: 'Dresden', land: 'Deutschland', distanz_km: 476 },
  { stadt: 'Bern', land: 'Schweiz', distanz_km: 478 },
  { stadt: 'London', land: 'Vereinigtes Königreich', distanz_km: 497 },
  { stadt: 'Rostock', land: 'Deutschland', distanz_km: 503 },
  { stadt: 'Prag', land: 'Tschechien', distanz_km: 536 },
  { stadt: 'Kopenhagen', land: 'Dänemark', distanz_km: 646 },
  { stadt: 'Monaco', land: 'Monaco', distanz_km: 679 },
  { stadt: 'Ljubljana', land: 'Slowenien', distanz_km: 684 },
  { stadt: 'Wien', land: 'Österreich', distanz_km: 744 },
  { stadt: 'Bratislava', land: 'Slowakei', distanz_km: 799 },
  { stadt: 'Zagreb', land: 'Kroatien', distanz_km: 875 },
  { stadt: 'Dublin', land: 'Irland', distanz_km: 936 },
  { stadt: 'Budapest', land: 'Ungarn', distanz_km: 956 },
  { stadt: 'Warschau', land: 'Polen', distanz_km: 980 },
  { stadt: 'Oslo', land: 'Norwegen', distanz_km: 1025 },
  { stadt: 'San Marino', land: 'San Marino', distanz_km: 1025 },
  { stadt: 'Rom', land: 'Italien', distanz_km: 1090 },
  { stadt: 'Andorra la Vella', land: 'Andorra', distanz_km: 1105 },
  { stadt: 'Belgrad', land: 'Serbien', distanz_km: 1175 },
  { stadt: 'Vilnius', land: 'Litauen', distanz_km: 1220 },
  { stadt: 'Sarajevo', land: 'Bosnien und Herzegowina', distanz_km: 1250 },
  { stadt: 'Riga', land: 'Lettland', distanz_km: 1305 },
  { stadt: 'Podgorica', land: 'Montenegro', distanz_km: 1340 },
  { stadt: 'Sofia', land: 'Bulgarien', distanz_km: 1390 },
  { stadt: 'Tallinn', land: 'Estland', distanz_km: 1420 },
  { stadt: 'Madrid', land: 'Spanien', distanz_km: 1428 },
  { stadt: 'Helsinki', land: 'Finnland', distanz_km: 1508 },
  { stadt: 'Minsk', land: 'Belarus', distanz_km: 1500 },
  { stadt: 'Tirana', land: 'Albanien', distanz_km: 1515 },
  { stadt: 'Skopje', land: 'Nordmazedonien', distanz_km: 1540 },
  { stadt: 'Bukarest', land: 'Rumänien', distanz_km: 1610 },
  { stadt: 'Kiew', land: 'Ukraine', distanz_km: 1660 },
  { stadt: 'Chișinău', land: 'Moldau', distanz_km: 1680 },
  { stadt: 'Valletta', land: 'Malta', distanz_km: 1830 },
  { stadt: 'Lissabon', land: 'Portugal', distanz_km: 1856 },
  { stadt: 'Athen', land: 'Griechenland', distanz_km: 1968 },
  { stadt: 'Moskau', land: 'Russland', distanz_km: 2060 },
  { stadt: 'Reykjavík', land: 'Island', distanz_km: 2250 },
  { stadt: 'Ankara', land: 'Türkei', distanz_km: 2350 },
  { stadt: 'Nikosia', land: 'Zypern', distanz_km: 2460 },
  { stadt: 'Tiflis', land: 'Georgien', distanz_km: 3270 },
  { stadt: 'Jerewan', land: 'Armenien', distanz_km: 3490 },
  { stadt: 'Baku', land: 'Aserbaidschan', distanz_km: 3640 },
]
